version: '3.7'

services:

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    image: mysql:8
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - localnet
    ports:
      - "3306:3306"

  nodejs:
    environment:
      - NODE_ENV=development
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs
    depends_on:
      - mysql
    command: /bin/sh -c 'npm i && npm run debug'
    volumes:
      - ./nodejs:/home/node/app
    networks:
      - localnet
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - nodejs
    volumes:
      - ./nodejs/static:/home/node/app/static
    networks:
      - localnet
    ports:
      - "80:80"
      - "443:443"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql
    networks:
      - localnet
    ports:
      - "8080:8080"

networks:
  localnet:
