version: '3.7'

services:

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    image: mysql:8
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - localnet
    ports:
      - "3306"

  nodejs:
    environment:
      - NODE_ENV=production
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs
    depends_on:
      - mysql
    volumes:
      - static:/home/node/app/static
    networks:
      - localnet
    ports:
      - "3000"
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - nodejs
    volumes:
      - static:/home/node/app/static
    networks:
      - localnet
    ports:
      - "80:80"
      - "443:443"

volumes:
  static:

networks:
  localnet:
